### ISSUE TITLE
Setup WebSocket for Messaging Feature

### ISSUE THREAD

**Issue by crebollarramirez** [acmucsd-projects/fa2024-hack-team-2#27]
## Overview
The objective is to implement a WebSocket server within the existing Express.js application to enable real-time messaging among users. This feature will support secure and efficient communication in the application.

---

## Goals
1. Create a WebSocket server that integrates with the existing Express.js server.
2. Enable real-time messaging functionality between authenticated users.
3. ~~Ensure secure connections and proper authentication using a method like Google OAuth.~~ 
4. Support essential messaging features such as:
   - Broadcasting messages to specific users or groups.
   - Handling connection and disconnection events.

---

## Deliverables
- WebSocket server implementation integrated with the Express.js application.
- ~~Authentication middleware to verify user credentials (e.g., Google OAuth token) during WebSocket handshake.~~
- Codebase documentation and inline comments for easy maintenance.
- Unit tests to validate WebSocket connection and messaging functionality.

---

## Tasks
1. **Integrate WebSocket with Express.js**
   - Research and decide between libraries such as `ws`, `socket.io`, or `express-ws`.
   - Set up the WebSocket server to work alongside the existing HTTP server.

2. **Implement Messaging Logic** 
   - Enable sending and receiving messages between users.
   - Include event handlers for user connection, disconnection, and errors.
   - Include chat history, so sent and received messages are saved.
   - Optionally, support message broadcasting to groups or rooms.

3. **Secure the WebSocket Server**
   - Use `wss://` (WebSocket Secure) protocol for encrypted communication.
   - ~~Implement rate limiting to prevent abuse.~~

4. **Write Tests and Documentation**
   - Unit tests for WebSocket authentication and messaging logic.
   - Documentation for developers on how to use and extend the WebSocket feature.

---

## Acceptance Criteria
- ~~Users can establish a WebSocket connection only after successful authentication.~~
- Messages can be exchanged securely and in real time between connected users.
- Proper error handling is implemented for invalid connections and messaging issues.
- Unit tests provide at least 80% code coverage for the WebSocket implementation.

---

## Additional Notes
- Look into message persistence or logging for future feature expansions, such as chat history.

---

## References
- [WebSocket API Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API)
- [Node.js `ws` Library](https://github.com/websockets/ws)

---

## What to do after issue is closed
Once the websocket is established and this issue is completed. We should add authentication to the websockets. To do this, refer to this issue: #28

**Comment by watawada** [comment]
Latest Commit: Implemented user messaging to the hard-coded bots. The messages save on the local mongodb database, but persistent messages on the chat has not been implemented. I added some receive message code, but I won't know if it works properly until user to user chatting is implemented. I added some messaging logic surrounding conversation ids (such as having the socket join a 'room'), but won't be fully implemented until user IDs are saved.
